# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Emergency App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Emergency App
pod 'Firebase/Core'
pod 'Firebase/Messaging'

  target 'Emergency AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Emergency AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
